In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('/Users/berk/Desktop/beer_reviews/beer_reviews.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 13 columns):
 #   Column              Non-Null Count    Dtype
---  ------              --------------    -----
 0   brewery_id          1586614 non-null  int64
 1   brewery_name        1586599 non-null  object
 2   review_time         1586614 non-null  int64
 3   review_overall      1586614 non-null  float64
 4   review_aroma        1586614 non-null  float64
 5   review_appearance   1586614 non-null  float64
 6   review_profilename  1586266 non-null  object
 7   beer_style          1586614 non-null  object
 8   review_palate       1586614 non-null  float64
 9   review_taste        1586614 non-null  float64
 10  beer_name           1586614 non-null  object
 11  beer_abv            1518829 non-null  float64
 12  beer_beerid         1586614 non-null  int64
dtypes: float64(6), int64(3), object(4)
memory usage: 157.4+ MB

In [4]:
df.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [6]:
df.drop(columns={'brewery_id', 'review_time', }, inplace=True)

In [7]:
#let's find out stucules reviews
df[df.review_profilename.isin(['stcules'])]

,brewery_name,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,Vecchio Birraio,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,Vecchio Birraio,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,Vecchio Birraio,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,Vecchio Birraio,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
1551,Landhausbräu Koller,4.0,3.5,3.5,stcules,Munich Dunkel Lager,3.5,4.0,Kollers Naturtrüb Dunkel,NaN,40395
...,...,...,...,...,...,...,...,...,...,...,...
1584791,Bi-Du,4.0,3.5,4.0,stcules,Oatmeal Stout,4.0,4.0,Black Mamba,5.0,43991
1584792,Bi-Du,4.0,3.0,2.5,stcules,Belgian Pale Ale,3.5,3.5,Ley Line,6.0,34271
1586165,Bierbrouwerij 't Vølendam,2.0,2.5,3.0,stcules,Bock,2.0,2.0,Vølenbock,6.5,26992
1586297,Brauerei Lasser GmbH,3.5,2.5,3.5,stcules,Munich Dunkel Lager,3.0,3.0,Lasser Dunkel,NaN,17734
1586299,Brauerei Lasser GmbH,4.0,3.5,3.0,stcules,German Pilsener,3.0,3.5,Lasser Premium Pils,NaN,17187

He/She has 1788 beer taste reviews

In [9]:
stcules_beer_choices = df[df.review_profilename.isin(['stcules'])].beer_style.unique()
len(stcules_beer_choices)

92

He/She has 92 different beer taste review